This is makeindex, version 2.16 [MiKTeX 24.4].
Scanning style file ./diss_arndt.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file diss_arndt.acn....done (182 entries accepted, 0 rejected).
Sorting entries.....done (1552 comparisons).
Generating output file diss_arndt.acr....done (146 lines written, 0 warnings).
Output written in diss_arndt.acr.
Transcript written in diss_arndt.alg.
